Repository cert-manager/klone, pull requests merged in 2024-01, with the labels that each got.

#5 Add OWNERS file
  OWNERS
Labels: dco-signoff: yes, lgtm, approved, size/S

#3 Add command descriptions to all commands
  cmd/add.go
  cmd/cmd.go
  cmd/init.go
  cmd/sync.go
  cmd/upgrade.go
Labels: dco-signoff: yes, size/M, lgtm, approved

#4 Add test for 'klone sync' and editKloneFile function
  .github/workflows/tests.yml
  example/klone.yaml
  pkg/mod/index.go
  pkg/mod/index_test.go
  test-e2e.sh
  test.sh
Labels: dco-signoff: yes, lgtm, approved, size/L

#6 Move canonicalize logic to dedicated function
  pkg/mod/index.go
  pkg/mod/index_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L
