Repository cert-manager/klone, pull requests merged in 2025-02, with the labels that each got.

#12 devel: Add makefile for development, target stable go in GHA
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .gitignore
  .goreleaser.yaml
  Makefile
  test-e2e.sh
Labels: dco-signoff: yes, lgtm, approved, size/L

#16 bug: only try to print goreleaser version after checkout
  .github/workflows/release.yml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#17 spelling: work
  cmd/add.go
  cmd/init.go
  pkg/sync/sync.go
Labels: dco-signoff: yes, lgtm, approved, size/S
